on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.10.2
          run_install: true
      - name: Build app
        run: pnpm build
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --exclude=index.html
        working-directory: dist
      - name: Deploy index.html to S3 bucket
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --exclude=* --include=index.html --cache-control max-age=0,no-cache,no-store,must-revalidate
        working-directory: dist
